In [3]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
import pandas as pd

df = pd.read_excel("Retail Sales Dataset.xlsx")
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-08-11 00:00:00,2016-11-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-08-11 00:00:00,2016-11-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-12-06 00:00:00,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-11-10 00:00:00,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-11-10 00:00:00,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [9]:
df.shape

(9994, 21)

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(2), str(13)
memory usage: 1.6+ MB

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

df[['Order Date', 'Ship Date']].head()

  Order Date  Ship Date
0 2016-08-11 2016-11-11
1 2016-08-11 2016-11-11
2 2016-12-06 2016-06-16
3 2015-11-10 2015-10-18
4 2015-11-10 2015-10-18

In [13]:
(df['Ship Date'] < df['Order Date']).sum()

np.int64(1708)

In [14]:
df['Date_Issue'] = df['Ship Date'] < df['Order Date']
df['Date_Issue'].value_counts()

Date_Issue
False    8286
True     1708
Name: count, dtype: int64

In [15]:
df['Profit Margin %'] = round((df['Profit'] / df['Sales']) * 100, 2)
df['Profit Margin %'].head()

0    16.00
1    30.00
2    47.00
3   -40.00
4    11.25
Name: Profit Margin %, dtype: float64

In [16]:
df['Month'] = df['Order Date'].dt.month
df['Quarter'] = df['Order Date'].dt.quarter
df['Year'] = df['Order Date'].dt.year

df[['Order Date', 'Month', 'Quarter', 'Year']].head()

  Order Date  Month  Quarter  Year
0 2016-08-11      8        3  2016
1 2016-08-11      8        3  2016
2 2016-12-06     12        4  2016
3 2015-11-10     11        4  2015
4 2015-11-10     11        4  2015

In [17]:
df['Days to Ship'] = (df['Ship Date'] - df['Order Date']).dt.days

df['Days to Ship'].head()

0     92
1     92
2   -173
3    -23
4    -23
Name: Days to Ship, dtype: int64

In [18]:
df[['Profit Margin %', 'Month', 'Quarter', 'Year', 'Days to Ship']].describe()

       Profit Margin %        Month      Quarter         Year  Days to Ship
count      9994.000000  9994.000000  9994.000000  9994.000000   9994.000000
mean         12.031390     7.174605     2.694617  2015.722233      9.347609
std          46.675436     3.428273     1.107635     1.123555     95.408385
min        -275.000000     1.000000     1.000000  2014.000000   -322.000000
25%           7.500000     4.000000     2.000000  2015.000000      2.000000
50%          27.000000     8.000000     3.000000  2016.000000      4.000000
75%          36.250000    10.000000     4.000000  2017.000000     61.000000
max          50.000000    12.000000     4.000000  2017.000000    214.000000

In [ ]:
df.to_csv("Retail_Sales_Cleaned.csv", index=False)
print("File saved successfully!")